spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BlueWhale?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    timeout: 6000 # 连接超时时间
    cache:
      type: redis # 指定缓存类型为Redis

server:
  port: 8080

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName: bluewhale38



alipay:
  appId: 9021000137604157
  appPrivateKey:
  alipayPublicKey:
  notifyUrl: http://bluewhale.nat300.top/api/ali/notify
  returnUrl: http://bluewhale.nat300.top/api/ali/returnUrl
  charset: utf-8
  sign-type: RSA2
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/bluewhale.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: "logs/bluewhale-%d{yyyy-MM-dd-HH-mm}.%i.log"
      max-history: 30




