package com.seecoder.BlueWhale.enums;

public enum ProductTypeEnum {
	/*食品分类*/
	FOOD,DRINK,SNACK,OTHERS_FOOD,
	/*服饰分类*/
	CLOTHES,JACKET,TROUSERS, OTHERS_CLOTHES,
	/*家具分类*/
	FURNITURE,OFFICE_FURNITURE,DAILY_FURNITURE,OTHERS_FURNITURE,
	/*电子产品分类*/
	ELECTRONICS,PHONE,COMPUTER,OTHERS_ELECTRONICS,
	/*娱乐产品分类*/
	ENTERTAINMENT,BOARD_GAME,CHESS,OTHERS_ENTERTAINMENT,
	/*体育用品分类*/
	SPORTS,BALL,EQUIPMENT,OTHERS_SPORTS,
	/*奢侈品分类*/
	LUXURY,HANDBAG,ACCESSORY,OTHERS_LUXURY,
	/*其他商品*/
	OTHERS
}
